# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Group name'),
        ),
    ]
