# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0003_auto_20170504_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='kind',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
