# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0004_auto_20170504_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Image name'),
        ),
    ]
