# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0005_answer_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Button text')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='faq_app.Answer', verbose_name='Answer')),
            ],
        ),
    ]
