# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0006_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 18, 23, 15, 21, 543672), verbose_name="Survey's datetime"),
        ),
    ]
